config/routes.rb
Rails.application.routes.draw do
  resources :owners
  resources :companies
  root 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
	validates :nameCo, presence: true, uniqueness: true
	validates :address, presence: true
	validates :city, presence: true

	has_many :owner
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  validates :nameOw, presence: true
  belongs_to :company
  has_attached_file :file
  validates_attachment_presence :file
  validates_attachment_content_type :file, :content_type => ["application/pdf", "application/msword", "application/vnd.ms-office application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"], :message => ', Only PDF or text files are allowed. '

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
       format.html { redirect_to @company, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:nameCo, :address, :city, :email, :phone)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:nameOw, :company_id, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="">Company name</label><br>
    <%= f.text_field :nameCo %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="addOwners"></div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companie Lists</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.id %></td>
        <td><b><%= link_to company.nameCo, company %></b></td>
        <td><%= company.address %></td>
        <td><%= company.city %></td>
        <td><%= company.email %></td>
        <td><%= company.phone %></td>
        <td><a href="/owners/new/?<%= company.id %>"><%=image_tag("add.png")%> Add Owner</a></td>
        <td><%= link_to image_tag("show.png"), company %></td>
        <td><%= link_to image_tag("edit.png"), edit_company_path(company) %></td>
        <td><%= link_to image_tag("delete.png"), company, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to image_tag("add.png")+' New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<%= link_to image_tag("edit.png"), edit_company_path(@company), class: 'float-right' %>

<p id="notice"><%= notice %></p>

<h1> <%= @company.nameCo %></h1>

<div class="details">
  <p>
    <strong>Address:</strong>
    <%= @company.address %>
  </p>

  <p>
    <strong>City:</strong>
    <%= @company.city %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @company.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @company.phone %>
  </p>
</div>
<label>  Directors and beneficial owners</label>

<% @company.owner.each do |owner| %>
<div class="owner">
  <b><%= owner.nameOw %></b> <br>
  <%= link_to image_tag("delete.png", width: '20'), owner, method: :delete, class: 'float-right' %> 
  <%= link_to 'Link File', owner.file.url, target: :_blank, class: 'link-file' %>
</div>
<% end %>

<a href="/owners/new/?<%= @company.id %>"><%=image_tag("add.png")%> Add Owner</a>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Companies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<div class="title">Ruby App by Cristhian Santana</div>
</header>
<nav class="main-menu">
  <ul>
    <li><%= link_to "Companies",  :companies %></li>
    <li><%= link_to "Owners",   :owners %></li>
  </ul>
</nav>
<div class="main-content">
	<%= yield %>
</div>


</body>
</html>

app/views/owners/_form.html.erb
<%= form_for @owner, :html => {:multipart => true}  do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Name Owner</label><br>
    <%= f.text_field :nameOw %>
  </div>
  <div class="field">
    <label>Company Id</label><br>
    <%= f.collection_select :company_id, Company.all, :id, :nameCo %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Edit director and beneficial owner</h1>

<%= render 'form' %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Directors and beneficial owners</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><b><%= link_to owner.nameOw, owner %></b></td>
        <td><%= owner.company.nameCo %></td>
        <td><%= link_to image_tag("show.png"), owner %></td>
        <td><%= link_to image_tag("edit.png"), edit_owner_path(owner) %></td>
        <td><%= link_to image_tag("delete.png"), owner, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to image_tag("add.png")+' New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New director and beneficial owner</h1>

<%= render 'form' %>

<script>
	var url = window.location,
		urlString = url.toString();
		companyId = urlString.split( '?' )[1],
		option = '#owner_company_id option[value="'+companyId+'"]';
	
	$(option).attr("selected",true);
</script>

app/views/owners/show.html.erb
<%= link_to image_tag("edit.png"), edit_owner_path(@owner), class: 'float-right' %>

<p id="notice"><%= notice %></p>

<h1><%= @owner.nameOw %></h1>
<div class="details">
	<p>
	  <strong>File:</strong>
	  <%= link_to 'Link', @owner.file.url, target: :_blank, class: 'link-file' %>
	</p>

	<p>
	  <strong>Company:</strong>
	  <%= @owner.company.nameCo %>
	</p>
</div>